/*
Aurora PostgreSQL pgvector schema for the RAG proof of concept.

The embedding column uses vector(1024) because Titan Text Embeddings V2 defaults
to 1024 dimensions. If VECTOR_DIM is changed to 512 or 256, the application
schema bootstrap replaces vector(1024) with the configured dimension before
executing this file.

The HNSW index uses vector_cosine_ops because embeddings are normalized and the
application orders by the pgvector cosine distance operator <=>. Parameters are
set to m = 16 and ef_construction = 256 as a balanced PoC default: m controls
connections per layer, while ef_construction trades index build time for recall.
At query time, tune hnsw.ef_search per session for higher recall or lower latency.
*/

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  chunk_index int NOT NULL,
  content text NOT NULL,
  embedding vector(1024) NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE (source, chunk_index)
);

CREATE INDEX IF NOT EXISTS documents_embedding_hnsw
ON documents
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 256);
